version: '3'
services:
  react-app:
    image: react-app
    build: ./client/
    ports:
      - "5173:5173"
    networks:
      - notes-app
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    build: ./server/
    ports:
      - "5000:5000"
    env_file: ./server/.env
    networks:
      - notes-app
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
networks:
  notes-app:
    driver: bridge

